### ISSUE TITLE
RabbitQueue as a parameter for a router handle

### ISSUE THREAD

**Issue by tmnhy** [Lancetnik/Propan#101]
**Describe the bug**
If you pass a RabbitQueue instead of a string to a router handle method, an error occurs at the BrokerRouter model level.

**To Reproduce**
```python
from propan import PropanApp
from propan.brokers.rabbit import RabbitBroker, RabbitQueue, RabbitRouter

app = PropanApp()
router = RabbitRouter()

@router.handle(RabbitQueue('test', durable=True))
async def test(body):
    print(body)

broker = RabbitBroker(...)
broker.include_router(router)
app.set_broker(broker)
```

**Screenshots**
![image](https://github.com/Lancetnik/Propan/assets/16719797/5d7ab607-a9f5-4b80-94f1-6802451edaa9)

**Comment by maciossek** [comment]
I know this is totally unrelated, but what lib is responsible for your error output?

**Comment by Lancetnik** [comment]
> I know this is totally unrelated, but what lib is responsible for your error output?

This is the `typer` with the `rich`

**Comment by Lancetnik** [comment]
@tmnhy thanks one more time! The job is done. I hope you wil get a pleasure working with the **Propan**.

**Comment by tmnhy** [comment]
@Lancetnik thanks, it's working now!
