### ISSUE TITLE
Bug: propan run chokes on relative imports in the main script

### ISSUE THREAD

**Issue by maxalbert** [Lancetnik/Propan#118]
First of all, massive thanks to @Lancetnik for creating this amazing project and making it available. Despite its young state it is extremely impressive and already helped me save a huge amount of time and headache while trying to get a message-based architecture to work for my current project. Kudos! 👏 

---

**Describe the bug**

The CLI command `propan run` exits with an error when there is a relative import present.

**To Reproduce**

1) Working example

   Here is a minimal example that works as expected. It consists of two files: `serve.py` (the main script) and `greeting.py` (containing a helper function that is imported in the main script).

   ```python
   # Contents of serve.py

   from propan import PropanApp
   from greeting import hello_world

   propan_app = PropanApp()

   @propan_app.on_startup
   async def say_hello():
       hello_world()
   ```

   ```python
   # Contents of greeting.py
   
   def hello_world():
       print("Hello world!")
   ```

   Output:
   ```
   $ propan run serve:propan_app
   2023-07-31 11:58:46,497 INFO     - Propan app starting...
   Hello world!
   2023-07-31 11:58:46,497 INFO     - Propan app started successfully! To exit press CTRL+C
   ```

2. Failing example

   The only change to the previous example is to use a relative import:
   ```python
   # [...]
   from .greeting import hello_world
   # [... ]
   ```

   Output:
   ```python
   $ propan run serve:propan_app
   Traceback (most recent call last):

     File "./venv/bin/propan", line 8, in <module>
       sys.exit(cli())

     File "./venv/lib/python3.10/site-packages/propan/cli/main.py", line 100, in run
       _run(module=module, app=app, extra_options=extra, log_level=casted_log_level)

     File "./venv/lib/python3.10/site-packages/propan/cli/main.py", line 110, in _run
       propan_app = try_import_propan(module, app)

     File "./venv/lib/python3.10/site-packages/propan/cli/utils/imports.py", line 12, in try_import_propan
       propan_app = import_object(module, app)

     File "./venv/lib/python3.10/site-packages/propan/cli/utils/imports.py", line 40, in import_object
       loader.exec_module(mod)

     File "<frozen importlib._bootstrap_external>", line 883, in exec_module

     File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

     File "serve.py", line 4, in <module>
       from .greeting import hello_world

   ModuleNotFoundError: No module named 'mode.greeting'
   ```
**Expected behavior**

I expect the relative import to work exactly as the first example and the Propan app to start successfully.

**Environment**

```
$ propan -v
Running Propan 0.1.5.15 with CPython 3.10.4 on Darwin
```

**Comment by Lancetnik** [comment]
@maxalbert thanks for your kind words and contribution too! I am glad that the project is helpful for you.

About the Issue. It looks like a closed one for me: https://github.com/Lancetnik/Propan/issues/98

The thing you talking about is not the **Propan** errors, it is the way python imports works

If you have the following project structure

```code
├── app
│   ├── main.py
│   ├── another.py
```

You can't import `another.py` from `main.py` relatively

```python
from .another import *  # wrong import
```

Just check it in the regular python code. Also, to be sure, that is not the **Propan** exception, just run your project example like a regular python script:

```python
app = Propan(app)

if __name__ == "__main__":
    asyncio.run(app.run())
```

And

```bash
python serve.py
```

If the regular python calling will execute correct, but `propan run ...` fails, please come again with more information about your project structer. If it is a bug endeed, let's fix it together.

**Comment by maxalbert** [comment]
Thanks for the quick reply and the explanation, @Lancetnik. I tried your suggestion to run the script as a regular Python script without `propan run`, and got the error you predicted: `ImportError: attempted relative import with no known parent package`. So this is indeed not a Propan error and the issue can be closed.

**Comment by Lancetnik** [comment]
@maxalbert anyway, thanks for the Issue. Be free to report of anything you feel like a bug. Also, you can join to the discord to get even quickly response and take a part of our community.

And one more thing: if you are using **Propan** and have pleasure of it, please tell others about your case in the discussions https://github.com/Lancetnik/Propan/discussions/categories/show-and-tell

I need to collect some feedback to correct the project course and proof a new users that project is using and helpful for others.
