### ISSUE TITLE
Feature: Marshmallow support along with pydantic?

### ISSUE THREAD

**Issue by shouldsee** [Lancetnik/Propan#131]
Thank you for this wonderful library! Really like this idea!

To suggest an idea or ask about a feature, a new Message Broker supporting or something else, please follow this template:

**Is your feature request related to a problem? Please describe.**
My project uses marshmellow. Want to use propan but not sure how to integrate

**Describe the solution you'd like**
A procedure to integrate propan with marshmallow message schemas

**Feature code example**
NA

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by Lancetnik** [comment]
@shouldsee, hi there! Thanks for you kind feedback
Unfotunatelly, I can't support all serialization libraries, but you have a way to integrate your custom one
Just use the `decode_message` argument

```python
from marshmallow import Schema, fields

from propan import RabbitBroker
from propan.brokers.rabbit import RabbitMessage
from propan.annotations import Logger


broker = RabbitBroker()
app = PropanApp(broker)

class User(Schema):
    name = fields.Str()

async def decode(msg: RabbitMessage, original):
    return User().loads(msg.body)

@broker.handle("test", decode_message=decode_marshmallow)
async def handle(msg, logger: Logger):
    logger.info(msg)
```

Or you can scale this code to any Schema via a closure

```python
from marshmallow import Schema, fields

from propan import PropanApp, RabbitBroker
from propan.brokers.rabbit import RabbitMessage
from propan.annotations import Logger


broker = RabbitBroker()
app = PropanApp(broker)

class User(Schema):
    name = fields.Str()

def decode_marshmallow(schema: Schema):
    async def decode(msg: RabbitMessage, original):
        return schema.loads(msg.body)
    return decode

@broker.handle("test", decode_message=decode_marshmallow(User()))
async def handle(msg, logger: Logger):
    logger.info(msg)

@app.after_startup
async def test():
    await broker.publish({
        "name": "john"
    }, "test")

```

**Comment by shouldsee** [comment]
Many thanks! BTW may I ask how the api documentation is generated from pydantic models? My main objective is to auto-generate api doc....

**Comment by Lancetnik** [comment]
I am using pydantic '.json_schema()' to get information about payloads
Other staff is generated by Propan: servers information, channels, bindings, etc
BTW, I will add an ability to set schema manually in custom serialization case in the PropanV2
