### ISSUE TITLE
Bug: SQSBroker not consuming when Queue is empty on startup.

### ISSUE THREAD

**Issue by belinux** [Lancetnik/Propan#141]
**Describe the bug**
Whenever you start the app and the SQS queue is empty, messages are not consumed.

**To Reproduce**
Have an empty Queue on SQS (I'm mocking SQS with elasticmq docker) then start the app, if you start sending messages those are not consumed.

**Fix**
Identation issue on [propan.brokers.sqs.sqs_broker.py:375](https://github.com/Lancetnik/Propan/blob/5cc6c65a784a93316f9473b0f9786d162801e317/propan/brokers/sqs/sqs_broker.py#L375), it should reach the scope where `has_trash_messages` is defined

**Comment by Lancetnik** [comment]
@belinux thanks for so targeted issue!
Btw, I'll start working on **FastStream** SQS as soon as I'm done with a new Framework structure (the old one had some critical problems)

**Comment by belinux** [comment]
you are welcome @Lancetnik , I've been trying to continue the migration on my own but got a bit lost on the way.. thank you!
