### ISSUE TITLE
Add `publish_batch` method to KafkaBroker

### ISSUE THREAD

**Issue by Lancetnik** [Lancetnik/Propan#45]
Look for references at aiokafka [documentation](https://aiokafka.readthedocs.io/en/stable/examples/batch_produce.html)

**Comment by JonathanXu8** [comment]
Hi, this seems like a great first issue for me to work on. I'd like to look into this. Thanks!

**Comment by Lancetnik** [comment]
It's a great news! Waiting for your PR soon.

**Comment by Lancetnik** [comment]
@JonathanXu8 do you need some help? Or I can implement this feature by myself?
