### ISSUE TITLE
Body type in Kafka Broker

### ISSUE THREAD

**Issue by asarkhipov** [Lancetnik/Propan#48]
**Describe the bug**
Body type in Kafka Broker

**To Reproduce**

```python
import json

from propan import KafkaBroker, PropanApp
from pydantic import BaseModel

broker = KafkaBroker()
app = PropanApp(broker)


class Msg(BaseModel):
    data: str


def des(val: bytes):
    return json.loads(val.decode("utf-8"))


@broker.handle(
    "test-topic", auto_offset_reset="latest", value_deserializer=des
)
async def hello(msg: Msg):
    print(msg)


@app.after_startup
async def pub():
    msg = Msg(data="hi")
    await broker.publish(
        msg.json(),
        "test-topic",
    )

...
```

And steps to reproduce the behavior:

1. Add kafka broker data and run code

**Expected behavior**
I expect `{"data": "hi"}` in output

**Environment**
Running Propan 0.1.2.7 with CPython 3.10.10 on Linux

**Additional context**
It happens because PropanMessage expect only bytes in message body, but in this case it is dict. 
Maybe need to catch and raise exceptions when handling messages, or add other types to PropanMessage body

**Comment by Lancetnik** [comment]
I will think about different serialization types, but now your code is not following **Propan** way.

You need no care about message serialization by yourself, **Propan** do it itself. Here, you broke **Propan** serialization by sending `str` insteade `pydantic.BaseModel` or `dict`, so message was `content-type` is `plain/text` instead `application/json`. Also, you tries to deserealize your message before **Propan**, it's mistake too.

The following code is correct:
```python
from propan import KafkaBroker, PropanApp
from pydantic import BaseModel

broker = KafkaBroker()
app = PropanApp(broker)

class Msg(BaseModel):
    data: str

@broker.handle("test-topic", auto_offset_reset="latest")
async def hello(msg: Msg):
    print(msg)

@app.after_startup
async def pub():
    msg = Msg(data="hi")
    await broker.publish(msg, "test-topic",)
```

**Comment by asarkhipov** [comment]
I write like this, because not all messages have content-type application/json
```@broker.handle("test-topic", auto_offset_reset="latest")
async def hello(msg: Msg):
    print(msg)
``` - not work with text/plain, and add correct content-type may take a long time to all services. 
I get `ValidationError(model='hello', errors=[{'loc': ('msg',), 'msg': 'value is not a valid dict', 'type': 'type_error.dict'}])` and try convert value into dict with value_deserializer


I can write it like this (or with Annotated):
```
def parse(msg: str):
    return Msg.parse_raw(msg)

@broker.handle("test-topic", auto_offset_reset="latest")
async def hello(msg: Msg = Depends(parse)):
    print(msg)
```
But i need a parse function for every data type. Maybe you think add a content-type parameter for handler, or automatically try to parse text into model, if it possible

**Comment by Lancetnik** [comment]
**Propan** adds `content-type` to all messages, sended by `publish`, so it always know, how parse them

**Comment by asarkhipov** [comment]
Propan adds, but not all messages are sended by propan

**Comment by Lancetnik** [comment]
Sure, but I can't parse anything you send correct way. You should takes exactly what you sends.

**Comment by Lancetnik** [comment]
It's defenetelly like HTTP: you should specify correct `content-type` at all requests. Nobody can guarante, that you requests   parses correct with invalid headers.

**Comment by Lancetnik** [comment]
Anyway, I am working on integration custom parsing logic like `aiokafka` by `value_deserializer`. So it can be a decision what you want.

**Comment by asarkhipov** [comment]
Okay, thank you!
Also another example why you may need value deserializer:
```python
import brotli
from propan import KafkaBroker, PropanApp
from pydantic import BaseModel

broker = KafkaBroker()
app = PropanApp(broker)


class Msg(BaseModel):
    data: str


def des(val: bytes) -> dict:
    return brotli.decompress(val)


@broker.handle(
    "test-topic", auto_offset_reset="latest", value_deserializer=des
)
async def hello(msg: Msg):
    print(msg)


@app.after_startup
async def pub():
    msg = Msg(
        data="""
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><g transform="translate(256,256)scale(24)rotate(15)" style="fill:#fff;"><circle style="fill:#ea3" r="10"/><ellipse rx="2" ry="8"/><ellipse cx="5" rx="1" ry="4"/><ellipse cx="-5" rx="1" ry="4"/></g></svg>
        """
    )
    await broker.publish(
        brotli.compress(msg.json().encode("utf-8")),
        "test-topic",
        headers={"content-type": "application/octet-stream"},
    )
```
I may use application/json for propan to make it automatically parse, but it will be wrong header: it actually bytes

**Comment by Lancetnik** [comment]
Okay, I am working on this feature. It should be impemented soon. So, do we can close the Issue?
