### ISSUE TITLE
Stop consuming messages after reconnecting with RabbitMQ

### ISSUE THREAD

**Issue by didhat** [Lancetnik/Propan#50]
**Description**
Error while reconnecting to RabbitMQ. The reconnect happens fine thanks to aio_pika, but message consumption and processing stops.

**To Reproduce**

```python
from propan import PropanApp
from propan import RabbitBroker
from propan.brokers.rabbit.schemas import RabbitQueue, RabbitExchange

broker = RabbitBroker("amqp://guest:guest@localhost:5672/")

app = PropanApp(broker)


@broker.handle(RabbitQueue(name="test", durable=True), RabbitExchange(name="kek", durable=True))
async def test_handler(body):
    print(body)
```

And steps to reproduce the behavior:

1. Run Propan app from above and RabbitMQ broker
2. Post multiple posts in any way (everything works)
3. Restart RabbitMQ broker. The app will successfully reconnect
4. Publish some messages to `kek` exchange. They will be published successfully, but the Propan app will not process them. It will only do this on app restart

**Expected behavior**
After reconnecting to the broker, Propan should continue processing messages.

**Environment**
Running Propan 0.1.2.9 with CPython 3.11.2 on Linux

**Additional context**
I think the problem is caused by the `consume` method of `aio_pika.abc.AbstractRobustQueue`. If you consume messages in this way, after reconnecting aio_pika for some reason does not restore work.

**Comment by didhat** [comment]
The example uses `durable` queues and recovery after reconnect is pretty obvious. But, it is likely that the consumption of temporary queues should also be restored, and for this, in some cases, they still need to be recreated. For example, when the reconnect was caused by a restart of the RabbitMQ broker itself

**Comment by Lancetnik** [comment]
Thanks for the Issue. Wait for fixes today/tomorrow.

**Comment by Lancetnik** [comment]
@didhat, sorry, but I can't reproduce your behavior. I had started a rabbitmq:latest container, stop it, restart it, restart RabbitMQ inside the container... All scenarios work fine after a little bit of waiting. `aio-pika` reconnecting code looks fine too.
Is that repeatable behavior in your case or did it occur once?

If it is repeatable behavior for you, can you try the following `aio-pika` code too?

```python
import asyncio
import aio_pika

async def main():
    connection = await aio_pika.connect_robust(
        "amqp://guest:guest@127.0.0.1/"
    )

    queue_name = "test_queue"
    exchange = "test_exch"

    async with connection:
        channel = await connection.channel()

        exch = await channel.declare_exchange(exchange, durable=True)
        queue = await channel.declare_queue(queue_name, durable=True)
        await queue.bind(exch)

        async with queue.iterator() as queue_iter:
            async for message in queue_iter:
                async with message.process():
                    print(message.body)

asyncio.run(main())
```

If `aio-pika` will has an error too, moving the Issue to that library makes sence. If `aio-pika` has no errors, but **Propan** does, I will continue to work on this Issue.

**Comment by didhat** [comment]
The code you provided for `aio_pika` will work fine, I tested it too. But when using queue.consume(...) and also in Propan, the error occurs. I have restarted RabbitMQ by restarting the docker container and in this case Propan is not restored. Below I will add the docker-compose.yml that I used.

```docker-compose
version: "3.3"


services:
  rabbitmq:
    hostname: node1
    image: rabbitmq:3-management-alpine


    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.data/:/var/lib/rabbitmq/
```

1. Start rabbitmq - `docker-compose up -d`
2. Start Propan app from my first message - `propan run main:app `
3. Publish some messages, below is a simple python script that I use to do this.
4. Stop rabbitmq with `docker-compose down`
5. Start rabbitmq with `docker-compose up`
6. Restart script for publishing messages
7. There Propan stop consume messages 

Script for publishing
```python3
import aio_pika
import asyncio
from aio_pika import DeliveryMode, Message


async def main():
    conn = await aio_pika.connect_robust(
        url="amqp://guest:guest@localhost:5672/", timeout=10
    )
    ch = await conn.channel()

    exch = await ch.get_exchange("kek")

    while True:
        ll = "dsds".encode("utf-8")
        message = Message(
            body=ll, delivery_mode=DeliveryMode.PERSISTENT
        )
        await exch.publish(message, routing_key="test")
        await asyncio.sleep(3)

if __name__ == "__main__":
    asyncio.run(main())

```

If it still fails to reproduce the error, then we can contact somewhere by calling, I will share the screen and provide a full explanation

**Comment by Lancetnik** [comment]
@didhat wait a second: does the following `aio-pika` code reproduce your error?

```python
import asyncio
import aio_pika

async def consume(message):
    print(message)

async def main():
    connection = await aio_pika.connect_robust(
        "amqp://guest:guest@127.0.0.1/"
    )

    queue_name = "test"
    exchange = "kek"

    async with connection:
        channel = await connection.channel()

        exch = await channel.declare_exchange(exchange, durable=True)
        queue = await channel.declare_queue(queue_name, durable=True)
        await queue.bind(exch)

        await queue.consume(consume)

        try:
            await asyncio.Future()
        finally:
            await connection.close()

asyncio.run(main())
```

**Comment by didhat** [comment]
@Lancetnik This code works fine for me

**Comment by Lancetnik** [comment]
@didhat It was a really interesting: `aio-pika` stores information about restorable objects in `WeakSet`

```python
for handler in self.handlers:
          queue = await self._init_handler(handler)
          await queue.consume(func)
```

So, then this loop is out, python has no refs to `queue`, QC delete it and aio-pika forget about queues to restore

**Comment by didhat** [comment]
@Lancetnik Yes, I assumed that the problem is somewhere in `aio_pika`. It looks like this logic should be implemented in `Propan`, or is it worth creating an issue in aio_pika for this?

**Comment by Lancetnik** [comment]
@didhat I am just fixed it with last commit. Download 1.2.12 version, It should be fine.
I am waiting for a new challenges from u.

**Comment by didhat** [comment]
@Lancetnik Thank you for your framework, I hope in the future I will have time to implement something in the project myself

**Comment by Lancetnik** [comment]
It will be great! Help is always welcome. If you working with RabbitMQ, a new release should be iteresting for you. I am one step from RabbitMQ project AsyncAPI sheme generation and hosting right from Propan.
