### ISSUE TITLE
Relative imports and non-root import paths crash the app

### ISSUE THREAD

**Issue by FyZyX** [Lancetnik/Propan#98]
**Describe the bug**
All imports must be relative to the package root, which means the imports in subpackages must actually be incorrect for the app to run properly.

**To Reproduce**
Consider the template project produced by:
```shell
$ propan create async rabbit example
```

Now, in the `config` subpackage, look at `__init__.py`
```python
from config.settings import Settings, init_settings
```

This import path is incorrect, it should be something like
```python
from settings import Settings, init_settings
```

And steps to reproduce the behavior:

1. Update the import
2. Start the broker
3. Run the app `propan run example.app.serve:app --env=.env --reload`

This will produce a `ModuleNotFoundError` like so:
```
Traceback (most recent call last):
  File "/Users/xyz/.pyenv/versions/3.11.3/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/xyz/.pyenv/versions/3.11.3/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/xyz/venv/lib/python3.11/site-packages/propan/cli/supervisors/utils.py", line 47, in subprocess_started
    t(*args)
  File "/Users/xyz/venv/lib/python3.11/site-packages/propan/cli/main.py", line 110, in _run
    propan_app = try_import_propan(module, app)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xyz/venv/lib/python3.11/site-packages/propan/cli/utils/imports.py", line 12, in try_import_propan
    propan_app = import_object(module, app)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xyz/venv/lib/python3.11/site-packages/propan/cli/utils/imports.py", line 40, in import_object
    loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/xyz/example/app/serve.py", line 7, in <module>
    from config import init_settings
  File "/Users/xyz/example/app/config/__init__.py", line 1, in <module>
    from settings import Settings, init_settings
ModuleNotFoundError: No module named 'settings'
```

**Expected behavior**
Import paths should respect the package hierarchy. We should also be able to use relative imports in subpackages, which currently break the app as well.

**Environment**
```
Running Propan 0.1.5.4 with CPython 3.11.3 on Darwin
```

**Additional context**
Obviously this is related to the dynamic importing procedures in `propan.cli.utils.imports`. I've tried a couple of different approaches, but I can't get the package imports to resolve correctly. At the moment, any module that is imported into the main app must use import paths relative to the package root, which is nuts.

This is actually very frustrating as it forces developers to use incorrect import paths in their code, making it impossible to reuse code in those module outside the context of `propan`. There are other issues with improper import paths as well, so it is extremely important to ensure that normal package loading works as expected.

**Comment by Lancetnik** [comment]
@FyZyX python relative imports should start with a [dot](https://docs.python.org/3/reference/import.html#submodules)

So, your example with

```python
from settings import Settings, init_settings
```

Is incorrect from the Python view, not the Propan. If you want to use relative import it should looks like

```python
from .settings import Settings, init_settings
```

And this example works fine.

You can check your imports are correct by running application like a regular Python script by

```python
if __name__ == "__main__":
    app.run()
```

and

```console
python serve.py
```

If this way to run application is working fine, but Propan CLI is fault - please, give me information about your application directory tree and broken imports.

**Comment by Lancetnik** [comment]
@FyZyX so did you try failing imports with manual python calling, as I said?

```console
python serve.py
```

**Comment by Lancetnik** [comment]
Python always looking packages from the root directory, where you call the script.
So, there no *subpackage* and you can't import subpackages relative it's directory.

You attempt to import - is invalid Python code at all, it's not the **Propan** bug

```python
from .. import model
```

Should looks like

```python
import model
```

Cuz the model is placed in the same level with your calling script

Also, about `settings.py`:
> Using just settings, while it's not technically a relative import path, is relative to the subpackage, not the root package, which is my point.

It's just a your point, but, unfortunatelly, not the Python point of view. It tries to import packages according to [`sys.path`](https://docs.python.org/3/library/sys.html#sys.path).

Please, give me example, working in python, but not working with the **Propan CLI**

**Comment by FyZyX** [comment]
Okay, my apologies, the real problem is having the main script inside the package to begin with. When we run a Python module as a script, it indeed does use the `PYTHONPATH` for all imports, which means relative imports in subpackages will fail. This is in fact normal Python behavior, so it is not a problem with Propan itself.

In order to get around this issue, I've pulled the main script out of the package and imported the package directly into the main script. This appears to resolve the import problems. Amazingly I'd never run into a situation like this before, probably because I don't usually keep my application scripts inside a package. I appreciate your fast responses and willingness to engage on the issue.

Fundamentally, this is about project structure, so while Propan is working correctly, complex package structures may become problematic for users if they base their project on one of the starter templates. For example, this would happen in they add additional modules in the same `app` package as the `serve` script and attempt to import those modules in subpackages as I did. Again, you're right, no need for code changes, but it might help to add some documentation around this, or potentially restructure the starter templates. I can document my findings if it helps you. Thanks again for working through this with me, I appreciate your patience. I'll close this issue as my initial report is indeed incorrect.

**Comment by Lancetnik** [comment]
@FyZyX thanks for you feedback. Changing the starting packages make a sence. But, I think the same structure is a typical for http-python packages (with the one entrypoin script and directories to import). Do you have any suggestion about different structure?

**Comment by Lancetnik** [comment]
@FyZyX sorry for leaving this problem for a long time. As you can see, we have an another Issue with relative imports.
Obviously the current template project structure is not clear enough to use it in a comfortable way.

Thus, we need to refactor it and I preffer the 3rd example from the proposed.

If you are interested in a contribution, I will be glad to merge your PR with this changes.
